version: "3.8"

services:
  deko:
    container_name: "deko"
    build:
      dockerfile: Dockerfile.deko
      context: .
    ports:
      - "9000:9000"
    networks:
      - deko-network

  deko-bridge:
    container_name: "deko-bridge"
    build:
      dockerfile: Dockerfile.dekobridge
      context: .
    ports:
      - "50051:50051"
    networks:
      - deko-network

networks:
  deko-network:
    driver: bridge
