# Use a minimal base image
FROM ubuntu:latest

# Set the working directory inside the container
WORKDIR /app

ENV SANDBOX_ENV="true"
# Copy the compiled Go binary into the container
COPY /deko /app/

# Set the entrypoint for the container
CMD ["/app/deko"]

