// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: deko_interface.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WSInputInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId   string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code        string `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Language    string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Format      bool   `protobuf:"varint,5,opt,name=format,proto3" json:"format,omitempty"`
	MessageType int64  `protobuf:"varint,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
}

func (x *WSInputInterface) Reset() {
	*x = WSInputInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deko_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSInputInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSInputInterface) ProtoMessage() {}

func (x *WSInputInterface) ProtoReflect() protoreflect.Message {
	mi := &file_deko_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSInputInterface.ProtoReflect.Descriptor instead.
func (*WSInputInterface) Descriptor() ([]byte, []int) {
	return file_deko_interface_proto_rawDescGZIP(), []int{0}
}

func (x *WSInputInterface) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WSInputInterface) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WSInputInterface) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WSInputInterface) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *WSInputInterface) GetFormat() bool {
	if x != nil {
		return x.Format
	}
	return false
}

func (x *WSInputInterface) GetMessageType() int64 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type WSOutputInterface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output     string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error      string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	MessageId  string `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	StatusCode int64  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *WSOutputInterface) Reset() {
	*x = WSOutputInterface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deko_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WSOutputInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSOutputInterface) ProtoMessage() {}

func (x *WSOutputInterface) ProtoReflect() protoreflect.Message {
	mi := &file_deko_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSOutputInterface.ProtoReflect.Descriptor instead.
func (*WSOutputInterface) Descriptor() ([]byte, []int) {
	return file_deko_interface_proto_rawDescGZIP(), []int{1}
}

func (x *WSOutputInterface) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WSOutputInterface) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WSOutputInterface) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WSOutputInterface) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WSOutputInterface) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_deko_interface_proto protoreflect.FileDescriptor

var file_deko_interface_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x6b, 0x6f, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x22, 0xb6, 0x01, 0x0a, 0x10, 0x57, 0x53, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9b, 0x01, 0x0a, 0x11, 0x57,
	0x53, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x60, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x57, 0x53, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0x1c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x57, 0x53, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_deko_interface_proto_rawDescOnce sync.Once
	file_deko_interface_proto_rawDescData = file_deko_interface_proto_rawDesc
)

func file_deko_interface_proto_rawDescGZIP() []byte {
	file_deko_interface_proto_rawDescOnce.Do(func() {
		file_deko_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_deko_interface_proto_rawDescData)
	})
	return file_deko_interface_proto_rawDescData
}

var file_deko_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deko_interface_proto_goTypes = []interface{}{
	(*WSInputInterface)(nil),  // 0: interface.WSInputInterface
	(*WSOutputInterface)(nil), // 1: interface.WSOutputInterface
}
var file_deko_interface_proto_depIdxs = []int32{
	0, // 0: interface.CompileService.CompileSource:input_type -> interface.WSInputInterface
	1, // 1: interface.CompileService.CompileSource:output_type -> interface.WSOutputInterface
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deko_interface_proto_init() }
func file_deko_interface_proto_init() {
	if File_deko_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deko_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSInputInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deko_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WSOutputInterface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deko_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deko_interface_proto_goTypes,
		DependencyIndexes: file_deko_interface_proto_depIdxs,
		MessageInfos:      file_deko_interface_proto_msgTypes,
	}.Build()
	File_deko_interface_proto = out.File
	file_deko_interface_proto_rawDesc = nil
	file_deko_interface_proto_goTypes = nil
	file_deko_interface_proto_depIdxs = nil
}
